# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:  
      - name: Install git 
        run: |
          apt-get install -y git
          git --version
          echo "Path is ... $PATH"
          PATH=$PATH:$(which git)
          echo "Path is ... $PATH"
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Install pre-commit hooks
        run: |
          pre-commit install
      - name: Run pre-commit hooks
        run: |
          pre-commit run
      
